# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lcs34TrDAzP7fWlJJWu6iPxRWkFF5O7c
"""

"""
House Price Prediction Dashboard — SINGLE FILE VERSION
=========================================================
Semua halaman (Home, EDA, Machine Learning, Feature Importance,
Perbandingan Model, Prediksi, Kesimpulan) digabung dalam satu file app.py.
Navigasi menggunakan sidebar radio, tanpa folder pages/.

Cara jalankan:
    streamlit run app.py

Struktur folder yang dibutuhkan:
    app.py
    data/data.csv
    models/  (akan dibuat otomatis saat training)
"""

import os
import sys
import time

import numpy as np
import pandas as pd
import joblib
import streamlit as st

import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score


# ════════════════════════════════════════════════════════════════
# KONFIGURASI HALAMAN (hanya dipanggil sekali, di awal file)
# ════════════════════════════════════════════════════════════════
st.set_page_config(
    page_title="House Price Prediction Dashboard",
    page_icon="🏠",
    layout="wide",
    initial_sidebar_state="expanded",
    menu_items={
        "Get Help": None,
        "Report a bug": None,
        "About": "🏠 House Price Prediction Dashboard v1.0 (single-file)",
    },
)

# ════════════════════════════════════════════════════════════════
# KONSTANTA PATH
# ════════════════════════════════════════════════════════════════
DATA_PATH   = "data.csv"
MODEL_DIR   = "models"
SCALER_PATH = os.path.join(MODEL_DIR, "scaler.pkl")
LR_PATH     = os.path.join(MODEL_DIR, "linear_regression.pkl")
RF_PATH     = os.path.join(MODEL_DIR, "random_forest.pkl")
ANN_PATH    = os.path.join(MODEL_DIR, "ann_model.keras")

DROP_COLS = ["date", "street", "country"]
CAT_COLS  = ["city", "statezip"]
TARGET    = "price"


# ════════════════════════════════════════════════════════════════
# CSS GLOBAL (isi dari style.css, di-inline langsung)
# ════════════════════════════════════════════════════════════════
CUSTOM_CSS = """
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap');

html, body, [class*="css"] { font-family: 'Inter', sans-serif; }
.main { background-color: #F0F4F8; }

.css-1d391kg, [data-testid="stSidebar"] {
    background: linear-gradient(160deg, #1A3A5C 0%, #1E5FA0 100%);
}
[data-testid="stSidebar"] .stMarkdown,
[data-testid="stSidebar"] label,
[data-testid="stSidebar"] p { color: #FFFFFF !important; }

.metric-card {
    background: white; border-radius: 16px; padding: 20px 24px;
    box-shadow: 0 2px 12px rgba(0, 82, 170, 0.08);
    border-left: 4px solid #1E5FA0;
    transition: transform 0.2s ease, box-shadow 0.2s ease; height: 100%;
}
.metric-card:hover { transform: translateY(-2px); box-shadow: 0 6px 20px rgba(0, 82, 170, 0.15); }
.metric-card .metric-label {
    font-size: 13px; font-weight: 500; color: #6B7280;
    text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 8px;
}
.metric-card .metric-value { font-size: 28px; font-weight: 700; color: #1A3A5C; line-height: 1.2; }
.metric-card .metric-icon { font-size: 24px; margin-bottom: 12px; }

.section-header {
    background: linear-gradient(90deg, #1E5FA0 0%, #2980B9 100%);
    color: white; padding: 16px 24px; border-radius: 12px; margin-bottom: 24px;
    font-size: 20px; font-weight: 600; letter-spacing: 0.01em;
}

.model-card {
    background: white; border-radius: 16px; padding: 24px;
    box-shadow: 0 2px 12px rgba(0,0,0,0.06); border-top: 4px solid #1E5FA0;
    text-align: center; transition: transform 0.2s ease;
}
.model-card:hover { transform: translateY(-3px); }
.model-card .model-icon { font-size: 40px; margin-bottom: 12px; }
.model-card .model-name { font-size: 16px; font-weight: 600; color: #1A3A5C; margin-bottom: 8px; }
.model-card .model-desc { font-size: 13px; color: #6B7280; line-height: 1.5; }

.best-badge {
    background: linear-gradient(90deg, #F59E0B, #EF4444); color: white;
    padding: 4px 12px; border-radius: 20px; font-size: 12px; font-weight: 600;
    display: inline-block; margin-left: 8px; animation: pulse 2s infinite;
}
@keyframes pulse { 0%, 100% { opacity: 1; } 50% { opacity: 0.8; } }

.price-high   { background: #FEE2E2; color: #991B1B; padding: 8px 20px; border-radius: 8px; font-weight: 600; font-size: 14px; display: inline-block; }
.price-medium { background: #FEF3C7; color: #92400E; padding: 8px 20px; border-radius: 8px; font-weight: 600; font-size: 14px; display: inline-block; }
.price-low    { background: #D1FAE5; color: #065F46; padding: 8px 20px; border-radius: 8px; font-weight: 600; font-size: 14px; display: inline-block; }

.prediction-box {
    background: linear-gradient(135deg, #1A3A5C, #1E5FA0); color: white;
    border-radius: 20px; padding: 32px; text-align: center;
    box-shadow: 0 8px 32px rgba(30, 95, 160, 0.25);
}
.prediction-box .pred-label {
    font-size: 14px; font-weight: 500; opacity: 0.8; margin-bottom: 8px;
    text-transform: uppercase; letter-spacing: 0.1em;
}
.prediction-box .pred-price { font-size: 48px; font-weight: 700; letter-spacing: -0.02em; margin-bottom: 8px; }

.dataframe { border-radius: 12px !important; overflow: hidden; border: none !important; }

[data-testid="stExpander"] { border: 1px solid #E5E7EB; border-radius: 12px; background: white; }

.stButton > button {
    background: linear-gradient(90deg, #1E5FA0, #2980B9); color: white; border: none;
    border-radius: 10px; padding: 10px 24px; font-weight: 600; font-size: 15px;
    transition: all 0.2s ease; width: 100%;
}
.stButton > button:hover {
    background: linear-gradient(90deg, #1A3A5C, #1E5FA0); transform: translateY(-1px);
    box-shadow: 0 4px 12px rgba(30, 95, 160, 0.3);
}

.stAlert { border-radius: 10px !important; }

.stTabs [data-baseweb="tab-list"] { gap: 8px; background: #EBF4FF; padding: 6px; border-radius: 10px; }
.stTabs [data-baseweb="tab"] { border-radius: 8px; font-weight: 500; color: #4B5563; }
.stTabs [aria-selected="true"] { background: #1E5FA0 !important; color: white !important; }

hr { border: none; height: 2px; background: linear-gradient(90deg, #1E5FA0, transparent); margin: 24px 0; }

.footer {
    text-align: center; color: #9CA3AF; font-size: 12px; padding: 24px 0 8px;
    border-top: 1px solid #E5E7EB; margin-top: 48px;
}
"""
st.markdown(f"<style>{CUSTOM_CSS}</style>", unsafe_allow_html=True)


# ════════════════════════════════════════════════════════════════
# FUNGSI UTILITAS (sebelumnya di utils.py)
# ════════════════════════════════════════════════════════════════
@st.cache_data(show_spinner="📂 Memuat dataset...")
def load_data() -> pd.DataFrame:
    """Memuat dataset dari CSV dan mengembalikan DataFrame mentah."""
    if not os.path.exists(DATA_PATH):
        st.error(f"❌ File dataset tidak ditemukan: `{DATA_PATH}`\n\nLetakkan `data.csv` di folder `data/`.")
        st.stop()
    return pd.read_csv(DATA_PATH)


@st.cache_data(show_spinner="⚙️ Memproses data...")
def preprocess_data(df: pd.DataFrame):
    """
    Preprocessing: drop kolom tak relevan, drop null, One-Hot Encoding,
    pisahkan X (fitur) dan y (target).
    """
    df = df.copy()
    cols_to_drop = [c for c in DROP_COLS if c in df.columns]
    df.drop(columns=cols_to_drop, inplace=True)
    df.dropna(inplace=True)

    y = df[TARGET].copy()
    X = df.drop(columns=[TARGET])

    cat_present = [c for c in CAT_COLS if c in X.columns]
    X = pd.get_dummies(X, columns=cat_present, drop_first=False)
    X = X.astype(float)

    return X, y, list(X.columns)


def save_model(model, path: str) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    joblib.dump(model, path)


def load_model(path: str):
    if os.path.exists(path):
        return joblib.load(path)
    return None


def save_ann(model, path: str = ANN_PATH) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    model.save(path)


def load_ann(path: str = ANN_PATH):
    if os.path.exists(path):
        try:
            import tensorflow as tf
            return tf.keras.models.load_model(path)
        except Exception:
            return None
    return None


def models_exist() -> bool:
    return all(os.path.exists(p) for p in [LR_PATH, RF_PATH, ANN_PATH, SCALER_PATH])


def compute_metrics(y_true, y_pred) -> dict:
    mae  = mean_absolute_error(y_true, y_pred)
    mse  = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    r2   = r2_score(y_true, y_pred)
    return {"MAE": mae, "MSE": mse, "RMSE": rmse, "R²": r2}


def format_currency(value: float) -> str:
    return f"${value:,.0f}"


def price_category(price: float, y: pd.Series) -> str:
    q33 = y.quantile(0.33)
    q66 = y.quantile(0.66)
    if price < q33:
        return "low"
    elif price < q66:
        return "medium"
    return "high"


def metric_card_html(icon: str, label: str, value: str) -> str:
    return f"""
    <div class="metric-card">
        <div class="metric-icon">{icon}</div>
        <div class="metric-label">{label}</div>
        <div class="metric-value">{value}</div>
    </div>
    """


def section_header(title: str) -> None:
    st.markdown(f'<div class="section-header">{title}</div>', unsafe_allow_html=True)


def footer() -> None:
    st.markdown(
        """
        <div class="footer">
            🏠 House Price Prediction Dashboard · Dibuat dengan Streamlit & ❤️ (single-file)
        </div>
        """,
        unsafe_allow_html=True,
    )


def render_sidebar_info() -> None:
    with st.sidebar:
        st.markdown("---")
        st.markdown(
            """
            <div style='text-align:center; color:rgba(255,255,255,0.7); font-size:12px;'>
                <b>🏠 House Price Dashboard</b><br>
                Versi 1.0.0 (single-file) · 2024<br><br>
                Algoritma: LR · RF · ANN
            </div>
            """,
            unsafe_allow_html=True,
        )


# ════════════════════════════════════════════════════════════════
# HALAMAN 1 — HOME
# ════════════════════════════════════════════════════════════════
def page_home():
    col_logo, col_title = st.columns([1, 5])

    with col_logo:
        st.markdown(
            "<div style='font-size:72px; text-align:center; padding-top:10px;'>🏡</div>",
            unsafe_allow_html=True,
        )

    with col_title:
        st.markdown(
            """
            <h1 style='color:#1A3A5C; font-size:32px; font-weight:700; margin-bottom:4px;'>
                Prediksi Harga Rumah
            </h1>
            <p style='color:#1E5FA0; font-size:17px; font-weight:500; margin-bottom:4px;'>
                Menggunakan Linear Regression, Random Forest, dan ANN
            </p>
            <p style='color:#6B7280; font-size:14px;'>
                Dashboard analitik profesional untuk penelitian machine learning di bidang properti
            </p>
            """,
            unsafe_allow_html=True,
        )

    st.markdown("---")

    with st.spinner("Memuat data..."):
        df_raw = load_data()
        X, y, feature_names = preprocess_data(df_raw)

    n_total = len(df_raw)
    n_train = int(n_total * 0.8)
    n_test  = n_total - n_train
    n_feat  = X.shape[1]

    section_header("📌 Tentang Penelitian")

    col_desc, col_illus = st.columns([3, 2])

    with col_desc:
        st.markdown(
            """
            <div style='background:white; border-radius:16px; padding:28px;
                        box-shadow:0 2px 12px rgba(0,82,170,0.07);'>
                <h3 style='color:#1A3A5C; margin-top:0;'>🎯 Latar Belakang</h3>
                <p style='color:#374151; line-height:1.8;'>
                    Harga properti dipengaruhi oleh banyak variabel yang saling berinteraksi,
                    mulai dari luas bangunan, lokasi, hingga kondisi fisik rumah.
                    Penelitian ini membandingkan tiga pendekatan machine learning untuk
                    memprediksi harga rumah secara akurat.
                </p>
                <h3 style='color:#1A3A5C;'>📐 Metodologi</h3>
                <ul style='color:#374151; line-height:2;'>
                    <li>Dataset: ~4.600 data properti</li>
                    <li>Preprocessing: One-Hot Encoding + StandardScaler (ANN)</li>
                    <li>Split: 80% Training / 20% Testing</li>
                    <li>Evaluasi: MAE, MSE, RMSE, R²</li>
                </ul>
                <h3 style='color:#1A3A5C;'>🔍 Variabel Target</h3>
                <p style='color:#374151;'><b>price</b> — Harga jual rumah dalam USD</p>
            </div>
            """,
            unsafe_allow_html=True,
        )

    with col_illus:
        st.markdown(
            """
            <div style='background:linear-gradient(135deg,#EBF4FF,#DBEAFE);
                        border-radius:16px; padding:40px 20px; text-align:center;
                        box-shadow:0 2px 12px rgba(0,82,170,0.07);'>
                <svg viewBox="0 0 200 160" xmlns="http://www.w3.org/2000/svg" width="200">
                  <rect width="200" height="160" fill="none"/>
                  <rect x="40" y="80" width="120" height="70" fill="#2980B9" rx="4"/>
                  <polygon points="30,80 100,20 170,80" fill="#1A3A5C"/>
                  <rect x="82" y="110" width="36" height="40" fill="#1A3A5C" rx="3"/>
                  <circle cx="113" cy="132" r="3" fill="#F59E0B"/>
                  <rect x="50" y="90" width="28" height="24" fill="#93C5FD" rx="3"/>
                  <line x1="64" y1="90" x2="64" y2="114" stroke="#1E5FA0" stroke-width="1.5"/>
                  <line x1="50" y1="102" x2="78" y2="102" stroke="#1E5FA0" stroke-width="1.5"/>
                  <rect x="122" y="90" width="28" height="24" fill="#93C5FD" rx="3"/>
                  <line x1="136" y1="90" x2="136" y2="114" stroke="#1E5FA0" stroke-width="1.5"/>
                  <line x1="122" y1="102" x2="150" y2="102" stroke="#1E5FA0" stroke-width="1.5"/>
                  <rect x="125" y="30" width="16" height="30" fill="#1A3A5C"/>
                  <circle cx="133" cy="25" r="6" fill="#D1D5DB" opacity="0.6"/>
                  <circle cx="140" cy="18" r="5" fill="#D1D5DB" opacity="0.4"/>
                  <rect x="0" y="148" width="200" height="12" fill="#86EFAC"/>
                  <polygon points="82,150 118,150 125,160 75,160" fill="#D1D5DB"/>
                  <circle cx="170" cy="30" r="14" fill="#FCD34D"/>
                </svg>
                <div style='color:#1A3A5C; font-weight:600; font-size:15px; margin-top:16px;'>
                    🏘️ Analisis Properti Cerdas
                </div>
                <div style='color:#6B7280; font-size:13px; margin-top:4px;'>
                    Prediksi Akurat Berbasis Data
                </div>
            </div>
            """,
            unsafe_allow_html=True,
        )

    st.markdown("<br>", unsafe_allow_html=True)

    section_header("📊 Statistik Dataset")
    c1, c2, c3, c4, c5 = st.columns(5)
    stats = [
        (c1, "🗃️", "Total Data",             f"{n_total:,}"),
        (c2, "📐", "Jumlah Fitur (encoded)",  f"{n_feat:,}"),
        (c3, "🎓", "Data Training (80%)",     f"{n_train:,}"),
        (c4, "🧪", "Data Testing (20%)",      f"{n_test:,}"),
        (c5, "💵", "Rata-rata Harga",         f"${y.mean():,.0f}"),
    ]
    for col, icon, label, val in stats:
        with col:
            st.markdown(metric_card_html(icon, label, val), unsafe_allow_html=True)

    st.markdown("<br>", unsafe_allow_html=True)

    section_header("🤖 Model Machine Learning")
    cm1, cm2, cm3 = st.columns(3)
    models_info = [
        (cm1, "📏", "Linear Regression",
         "Baseline model regresi linear sederhana. Cepat dan mudah diinterpretasikan."),
        (cm2, "🌲", "Random Forest",
         "Ensemble 200+ decision trees dengan bootstrapping untuk akurasi tinggi."),
        (cm3, "🧠", "Artificial Neural Network",
         "Deep learning 3-layer dengan EarlyStopping, cocok untuk pola non-linear kompleks."),
    ]
    for col, icon, name, desc in models_info:
        with col:
            st.markdown(
                f"""
                <div class="model-card">
                    <div class="model-icon">{icon}</div>
                    <div class="model-name">{name}</div>
                    <div class="model-desc">{desc}</div>
                </div>
                """,
                unsafe_allow_html=True,
            )

    st.markdown("<br>", unsafe_allow_html=True)

    section_header("📋 Variabel Penelitian")
    with st.expander("📂 Lihat daftar variabel lengkap", expanded=False):
        col_f1, col_f2 = st.columns(2)

        with col_f1:
            st.markdown("**🎯 Variabel Target**")
            st.dataframe(
                pd.DataFrame({"Kolom": ["price"], "Keterangan": ["Harga jual rumah (USD)"]}),
                hide_index=True, use_container_width=True,
            )

            st.markdown("**📥 Fitur Numerik**")
            num_feats = pd.DataFrame({
                "Kolom": ["bedrooms","bathrooms","sqft_living","sqft_lot","floors",
                          "waterfront","view","condition","sqft_above","sqft_basement",
                          "yr_built","yr_renovated"],
                "Keterangan": [
                    "Jumlah kamar tidur", "Jumlah kamar mandi", "Luas bangunan (sqft)",
                    "Luas tanah (sqft)", "Jumlah lantai", "Ada waterfront (0/1)",
                    "Nilai pemandangan (0–4)", "Kondisi rumah (1–5)",
                    "Luas lantai atas (sqft)", "Luas basement (sqft)",
                    "Tahun dibangun", "Tahun renovasi terakhir",
                ],
            })
            st.dataframe(num_feats, hide_index=True, use_container_width=True)

        with col_f2:
            st.markdown("**🔤 Fitur Kategorikal (One-Hot Encoded)**")
            cat_feats = pd.DataFrame({
                "Kolom": ["city", "statezip"],
                "Keterangan": ["Kota lokasi rumah", "Kode pos / state"],
            })
            st.dataframe(cat_feats, hide_index=True, use_container_width=True)

            st.markdown("**🗑️ Kolom Tidak Digunakan**")
            drop_feats = pd.DataFrame({
                "Kolom": ["date", "street", "country"],
                "Alasan": ["Tidak relevan (waktu)", "Terlalu spesifik", "Homogen (satu nilai)"],
            })
            st.dataframe(drop_feats, hide_index=True, use_container_width=True)

    footer()


# ════════════════════════════════════════════════════════════════
# HALAMAN 2 — EDA
# ════════════════════════════════════════════════════════════════
def page_eda():
    st.markdown("<h2 style='color:#1A3A5C;'>📊 Exploratory Data Analysis</h2>", unsafe_allow_html=True)
    st.markdown("Analisis mendalam terhadap distribusi dan hubungan antar variabel dalam dataset.")
    st.markdown("---")

    df = load_data()
    X, y, _ = preprocess_data(df)
    df_clean = df.copy()

    for c in ["date", "street", "country"]:
        if c in df_clean.columns:
            df_clean.drop(columns=[c], inplace=True)
    df_clean.dropna(inplace=True)

    tab1, tab2, tab3, tab4, tab5 = st.tabs([
        "📋 Statistik Deskriptif", "📈 Distribusi Harga", "🔗 Scatter Plot",
        "🌡️ Korelasi", "⚠️ Missing & Outlier",
    ])

    with tab1:
        section_header("📋 Statistik Deskriptif Dataset")
        col_a, col_b = st.columns([2, 1])

        with col_a:
            st.markdown("**Ringkasan Statistik Numerik**")
            desc = df_clean.describe().T.round(2)
            st.dataframe(desc, use_container_width=True)

        with col_b:
            st.markdown("**Informasi Dataset**")
            info_data = {
                "Info": ["Jumlah Baris", "Jumlah Kolom", "Tipe Data Numerik",
                         "Tipe Data Objek", "Memori (KB)"],
                "Nilai": [
                    f"{len(df_clean):,}", f"{df_clean.shape[1]}",
                    f"{df_clean.select_dtypes(include=np.number).shape[1]}",
                    f"{df_clean.select_dtypes(include='object').shape[1]}",
                    f"{df_clean.memory_usage(deep=True).sum() / 1024:.1f}",
                ],
            }
            st.dataframe(pd.DataFrame(info_data), hide_index=True, use_container_width=True)

            num_count = df_clean.select_dtypes(include=np.number).shape[1]
            cat_count = df_clean.select_dtypes(include="object").shape[1]
            fig_pie = px.pie(
                values=[num_count, cat_count], names=["Numerik", "Kategorikal"],
                color_discrete_sequence=["#1E5FA0", "#93C5FD"],
                title="Komposisi Tipe Kolom", hole=0.4,
            )
            fig_pie.update_layout(height=250, margin=dict(t=40, b=0, l=0, r=0))
            st.plotly_chart(fig_pie, use_container_width=True)

        st.markdown("**🔍 Sampel Data (10 baris pertama)**")
        st.dataframe(df_clean.head(10), use_container_width=True)

    with tab2:
        section_header("📈 Distribusi Harga Rumah")
        col1, col2 = st.columns(2)

        with col1:
            fig_hist = px.histogram(
                df_clean, x="price", nbins=60, title="Distribusi Harga Rumah",
                labels={"price": "Harga (USD)", "count": "Frekuensi"},
                color_discrete_sequence=["#1E5FA0"], opacity=0.8,
            )
            fig_hist.add_vline(x=df_clean["price"].mean(), line_dash="dash",
                               line_color="#EF4444", annotation_text="Mean")
            fig_hist.add_vline(x=df_clean["price"].median(), line_dash="dot",
                               line_color="#F59E0B", annotation_text="Median")
            fig_hist.update_layout(height=400, plot_bgcolor="white", paper_bgcolor="white", showlegend=False)
            st.plotly_chart(fig_hist, use_container_width=True)

        with col2:
            fig_box = px.box(
                df_clean, y="price", title="Box Plot Harga Rumah",
                labels={"price": "Harga (USD)"}, color_discrete_sequence=["#1E5FA0"],
                points="outliers",
            )
            fig_box.update_layout(height=400, plot_bgcolor="white", paper_bgcolor="white")
            st.plotly_chart(fig_box, use_container_width=True)

        st.markdown("**Distribusi Log(Price) — Lebih simetris untuk analisis**")
        df_clean["log_price"] = np.log1p(df_clean["price"])
        fig_log = px.histogram(
            df_clean, x="log_price", nbins=60, title="Distribusi Log(Harga) Rumah",
            labels={"log_price": "Log(Harga)", "count": "Frekuensi"},
            color_discrete_sequence=["#2980B9"], opacity=0.8,
        )
        fig_log.update_layout(height=300, plot_bgcolor="white", paper_bgcolor="white")
        st.plotly_chart(fig_log, use_container_width=True)

        if "city" in df_clean.columns:
            st.markdown("**🏙️ Top 10 Kota dengan Median Harga Tertinggi**")
            city_price = (
                df_clean.groupby("city")["price"].median().reset_index()
                .sort_values("price", ascending=False).head(10)
            )
            fig_city = px.bar(
                city_price, x="city", y="price", title="Median Harga per Kota (Top 10)",
                labels={"city": "Kota", "price": "Median Harga (USD)"},
                color="price", color_continuous_scale="Blues",
            )
            fig_city.update_layout(height=350, plot_bgcolor="white", paper_bgcolor="white",
                                   coloraxis_showscale=False)
            st.plotly_chart(fig_city, use_container_width=True)

    with tab3:
        section_header("🔗 Scatter Plot: Harga vs Fitur Numerik")
        scatter_opts = {
            "sqft_living": "Luas Bangunan (sqft)", "bedrooms": "Jumlah Kamar Tidur",
            "bathrooms": "Jumlah Kamar Mandi", "sqft_lot": "Luas Tanah (sqft)",
            "yr_built": "Tahun Dibangun", "sqft_above": "Luas Lantai Atas (sqft)",
        }

        col_sel1, col_sel2 = st.columns([1, 3])
        with col_sel1:
            x_var = st.selectbox("Pilih variabel X:", options=list(scatter_opts.keys()),
                                 format_func=lambda x: scatter_opts[x])

        color_col = "waterfront" if "waterfront" in df_clean.columns else None

        with col_sel2:
            fig_scatter = px.scatter(
                df_clean.sample(min(2000, len(df_clean)), random_state=42),
                x=x_var, y="price", color=color_col, trendline="ols",
                title=f"Price vs {scatter_opts[x_var]}",
                labels={"price": "Harga (USD)", x_var: scatter_opts[x_var]},
                color_discrete_sequence=["#1E5FA0", "#F59E0B"], opacity=0.6,
            )
            fig_scatter.update_layout(height=400, plot_bgcolor="white", paper_bgcolor="white")
            st.plotly_chart(fig_scatter, use_container_width=True)

        st.markdown("**🔢 Scatter Plot Grid (6 Fitur Utama)**")
        num_cols = ["sqft_living", "bedrooms", "bathrooms", "sqft_lot", "yr_built", "sqft_above"]
        num_cols = [c for c in num_cols if c in df_clean.columns]

        fig_grid = make_subplots(rows=2, cols=3,
                                 subplot_titles=[scatter_opts.get(c, c) for c in num_cols[:6]])
        sample_df = df_clean.sample(min(1000, len(df_clean)), random_state=42)

        for i, col_name in enumerate(num_cols[:6]):
            r, c = divmod(i, 3)
            fig_grid.add_trace(
                go.Scatter(x=sample_df[col_name], y=sample_df["price"], mode="markers",
                          marker=dict(color="#1E5FA0", opacity=0.4, size=5),
                          name=col_name, showlegend=False),
                row=r + 1, col=c + 1,
            )

        fig_grid.update_layout(height=500, plot_bgcolor="white", paper_bgcolor="white",
                               title_text="Scatter Plot: Price vs Fitur Numerik")
        st.plotly_chart(fig_grid, use_container_width=True)

    with tab4:
        section_header("🌡️ Correlation Heatmap")
        num_df = df_clean.select_dtypes(include=np.number)
        if "log_price" in num_df.columns:
            num_df = num_df.drop(columns=["log_price"])

        corr = num_df.corr().round(3)
        fig_heat = px.imshow(
            corr, text_auto=True, color_continuous_scale="RdBu_r",
            title="Correlation Matrix (Fitur Numerik)", aspect="auto", zmin=-1, zmax=1,
        )
        fig_heat.update_layout(height=600, coloraxis_colorbar=dict(title="Korelasi"))
        st.plotly_chart(fig_heat, use_container_width=True)

        st.markdown("**📊 Korelasi Setiap Fitur dengan Harga (price)**")
        if "price" in corr.columns:
            price_corr = corr["price"].drop("price").sort_values(ascending=False)
            fig_corr_bar = px.bar(
                x=price_corr.index, y=price_corr.values,
                labels={"x": "Fitur", "y": "Korelasi Pearson"},
                title="Korelasi Fitur Numerik dengan Price",
                color=price_corr.values, color_continuous_scale="RdBu_r",
            )
            fig_corr_bar.update_layout(height=350, plot_bgcolor="white",
                                       paper_bgcolor="white", coloraxis_showscale=False)
            st.plotly_chart(fig_corr_bar, use_container_width=True)

    with tab5:
        section_header("⚠️ Analisis Missing Value & Outlier")
        col_mv, col_out = st.columns(2)

        with col_mv:
            st.markdown("**🔍 Missing Value per Kolom**")
            raw_df = load_data()
            mv = pd.DataFrame({
                "Kolom": raw_df.columns,
                "Missing": raw_df.isnull().sum().values,
                "Persen (%)": (raw_df.isnull().sum().values / len(raw_df) * 100).round(2),
            })
            mv = mv[mv["Missing"] > 0] if mv["Missing"].sum() > 0 else mv
            st.dataframe(mv, hide_index=True, use_container_width=True)

            if mv["Missing"].sum() == 0:
                st.success("✅ Tidak ada missing value dalam dataset!")
            else:
                st.warning(f"⚠️ Ditemukan {mv['Missing'].sum()} missing value.")

        with col_out:
            st.markdown("**📦 Deteksi Outlier (IQR Method)**")
            outlier_cols = ["price", "sqft_living", "bedrooms", "bathrooms"]
            outlier_cols = [c for c in outlier_cols if c in df_clean.columns]

            outlier_info = []
            for col_o in outlier_cols:
                q1 = df_clean[col_o].quantile(0.25)
                q3 = df_clean[col_o].quantile(0.75)
                iqr = q3 - q1
                lower = q1 - 1.5 * iqr
                upper = q3 + 1.5 * iqr
                n_out = ((df_clean[col_o] < lower) | (df_clean[col_o] > upper)).sum()
                outlier_info.append({
                    "Kolom": col_o, "Q1": round(q1, 2), "Q3": round(q3, 2), "IQR": round(iqr, 2),
                    "Batas Bawah": round(lower, 2), "Batas Atas": round(upper, 2),
                    "Outlier": n_out, "Persen (%)": round(n_out / len(df_clean) * 100, 2),
                })

            st.dataframe(pd.DataFrame(outlier_info), hide_index=True, use_container_width=True)

        st.markdown("**📦 Box Plot Deteksi Outlier**")
        feat_box = st.selectbox("Pilih fitur:", outlier_cols, key="outlier_box")
        fig_out_box = px.box(
            df_clean, y=feat_box, title=f"Box Plot — {feat_box}",
            color_discrete_sequence=["#1E5FA0"], points="suspectedoutliers",
        )
        fig_out_box.update_layout(height=350, plot_bgcolor="white", paper_bgcolor="white")
        st.plotly_chart(fig_out_box, use_container_width=True)

    footer()


# ════════════════════════════════════════════════════════════════
# HALAMAN 3 — MACHINE LEARNING
# ════════════════════════════════════════════════════════════════
def build_ann(input_dim: int):
    import tensorflow as tf
    model = tf.keras.Sequential([
        tf.keras.layers.Input(shape=(input_dim,)),
        tf.keras.layers.Dense(256, activation="relu"),
        tf.keras.layers.BatchNormalization(),
        tf.keras.layers.Dropout(0.3),
        tf.keras.layers.Dense(128, activation="relu"),
        tf.keras.layers.BatchNormalization(),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(64, activation="relu"),
        tf.keras.layers.Dense(1),
    ])
    model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001), loss="mse", metrics=["mae"])
    return model


def train_all_models(X_train, X_test, y_train, y_test, n_estimators: int = 200):
    os.makedirs(MODEL_DIR, exist_ok=True)
    results = {}

    with st.spinner("🏃 Training Linear Regression..."):
        t0 = time.time()
        lr = LinearRegression()
        lr.fit(X_train, y_train)
        train_time_lr = time.time() - t0

        t1 = time.time()
        y_pred_lr = lr.predict(X_test)
        pred_time_lr = time.time() - t1

        save_model(lr, LR_PATH)
        metrics_lr = compute_metrics(y_test, y_pred_lr)
        metrics_lr["Training Time (s)"] = round(train_time_lr, 4)
        metrics_lr["Prediction Time (s)"] = round(pred_time_lr, 6)
        results["Linear Regression"] = {"metrics": metrics_lr, "y_pred": y_pred_lr, "model": lr}

    with st.spinner(f"🌲 Training Random Forest ({n_estimators} trees)..."):
        t0 = time.time()
        rf = RandomForestRegressor(n_estimators=n_estimators, random_state=42, n_jobs=-1)
        rf.fit(X_train, y_train)
        train_time_rf = time.time() - t0

        t1 = time.time()
        y_pred_rf = rf.predict(X_test)
        pred_time_rf = time.time() - t1

        save_model(rf, RF_PATH)
        metrics_rf = compute_metrics(y_test, y_pred_rf)
        metrics_rf["Training Time (s)"] = round(train_time_rf, 2)
        metrics_rf["Prediction Time (s)"] = round(pred_time_rf, 6)
        results["Random Forest"] = {"metrics": metrics_rf, "y_pred": y_pred_rf, "model": rf}

    with st.spinner("🧠 Training Artificial Neural Network..."):
        import tensorflow as tf

        scaler = StandardScaler()
        X_train_sc = scaler.fit_transform(X_train)
        X_test_sc  = scaler.transform(X_test)
        save_model(scaler, SCALER_PATH)

        ann = build_ann(X_train_sc.shape[1])
        early_stop = tf.keras.callbacks.EarlyStopping(monitor="val_loss", patience=15, restore_best_weights=True)

        t0 = time.time()
        history = ann.fit(
            X_train_sc, y_train, validation_split=0.1, epochs=200, batch_size=64,
            callbacks=[early_stop], verbose=0,
        )
        train_time_ann = time.time() - t0

        t1 = time.time()
        y_pred_ann = ann.predict(X_test_sc, verbose=0).flatten()
        pred_time_ann = time.time() - t1

        save_ann(ann, ANN_PATH)
        metrics_ann = compute_metrics(y_test, y_pred_ann)
        metrics_ann["Training Time (s)"] = round(train_time_ann, 2)
        metrics_ann["Prediction Time (s)"] = round(pred_time_ann, 4)
        results["ANN"] = {
            "metrics": metrics_ann, "y_pred": y_pred_ann, "model": ann,
            "history": history, "X_test_sc": X_test_sc,
        }

    return results


def page_ml():
    st.markdown("<h2 style='color:#1A3A5C;'>🤖 Machine Learning — Training & Evaluasi</h2>", unsafe_allow_html=True)
    st.markdown("Latih dan evaluasi tiga model prediksi harga rumah secara otomatis.")
    st.markdown("---")

    df = load_data()
    X, y, feature_names = preprocess_data(df)
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    with st.sidebar:
        st.markdown("### ⚙️ Pengaturan Training")
        n_trees = st.slider("Jumlah Trees (RF)", 50, 300, 200, 50)
        st.markdown("---")
        retrain = st.button("🔁 Retrain Semua Model", use_container_width=True)

    col_s1, col_s2, col_s3, col_s4 = st.columns(4)
    for col, icon, label, val in [
        (col_s1, "📚", "Training Data", f"{len(X_train):,}"),
        (col_s2, "🧪", "Testing Data", f"{len(X_test):,}"),
        (col_s3, "📐", "Jumlah Fitur", f"{X.shape[1]:,}"),
        (col_s4, "🌀", "Split Ratio", "80 : 20"),
    ]:
        with col:
            st.markdown(metric_card_html(icon, label, val), unsafe_allow_html=True)

    st.markdown("<br>", unsafe_allow_html=True)

    if retrain or not models_exist():
        st.info("⏳ Memulai proses training... Mohon tunggu.")
        results = train_all_models(X_train, X_test, y_train, y_test, n_estimators=n_trees)
        st.session_state["ml_results"] = results
        st.session_state["y_test"] = y_test
        st.session_state["X_test"] = X_test
        st.success("✅ Semua model berhasil dilatih dan disimpan!")
    else:
        if "ml_results" not in st.session_state:
            st.info("📂 Model sudah ada. Memuat dan mengevaluasi model tersimpan...")

            lr_loaded  = load_model(LR_PATH)
            rf_loaded  = load_model(RF_PATH)
            ann_loaded = load_ann(ANN_PATH)
            sc_loaded  = load_model(SCALER_PATH)

            results = {}

            if lr_loaded:
                t1 = time.time()
                y_pred = lr_loaded.predict(X_test)
                pt = time.time() - t1
                m = compute_metrics(y_test, y_pred)
                m["Training Time (s)"] = "—"
                m["Prediction Time (s)"] = round(pt, 6)
                results["Linear Regression"] = {"metrics": m, "y_pred": y_pred, "model": lr_loaded}

            if rf_loaded:
                t1 = time.time()
                y_pred = rf_loaded.predict(X_test)
                pt = time.time() - t1
                m = compute_metrics(y_test, y_pred)
                m["Training Time (s)"] = "—"
                m["Prediction Time (s)"] = round(pt, 6)
                results["Random Forest"] = {"metrics": m, "y_pred": y_pred, "model": rf_loaded}

            if ann_loaded and sc_loaded:
                X_test_sc = sc_loaded.transform(X_test)
                t1 = time.time()
                y_pred = ann_loaded.predict(X_test_sc, verbose=0).flatten()
                pt = time.time() - t1
                m = compute_metrics(y_test, y_pred)
                m["Training Time (s)"] = "—"
                m["Prediction Time (s)"] = round(pt, 4)
                results["ANN"] = {"metrics": m, "y_pred": y_pred, "model": ann_loaded}

            st.session_state["ml_results"] = results
            st.session_state["y_test"] = y_test
            st.session_state["X_test"] = X_test
        else:
            results = st.session_state["ml_results"]

    if "ml_results" not in st.session_state:
        st.warning("⚠️ Klik tombol 'Retrain' atau tunggu model di-load.")
        st.stop()

    results = st.session_state["ml_results"]
    y_test  = st.session_state.get("y_test", y_test)

    section_header("📊 Hasil Evaluasi Model")

    model_colors = {"Linear Regression": "#1E5FA0", "Random Forest": "#059669", "ANN": "#7C3AED"}

    tabs_models = st.tabs([
        f"📏 {k}" if k == "Linear Regression" else f"🌲 {k}" if k == "Random Forest" else f"🧠 {k}"
        for k in results.keys()
    ])

    for tab_m, (model_name, res) in zip(tabs_models, results.items()):
        with tab_m:
            metrics = res["metrics"]
            color   = model_colors.get(model_name, "#1E5FA0")

            mc1, mc2, mc3, mc4 = st.columns(4)
            metric_pairs = [
                (mc1, "📉", "MAE",  f"${metrics['MAE']:,.0f}"),
                (mc2, "📉", "MSE",  f"${metrics['MSE']:,.0f}"),
                (mc3, "📉", "RMSE", f"${metrics['RMSE']:,.0f}"),
                (mc4, "📈", "R²",   f"{metrics['R²']:.4f}"),
            ]
            for col, icon, label, val in metric_pairs:
                with col:
                    st.markdown(metric_card_html(icon, label, val), unsafe_allow_html=True)

            st.markdown("<br>", unsafe_allow_html=True)

            col_p, col_r = st.columns(2)
            y_pred = res["y_pred"]

            with col_p:
                sample_size = min(500, len(y_test))
                idx = np.random.choice(len(y_test), sample_size, replace=False)
                yt_sample = np.array(y_test)[idx]
                yp_sample = y_pred[idx]

                fig_ap = go.Figure()
                fig_ap.add_trace(go.Scatter(
                    x=yt_sample, y=yp_sample, mode="markers",
                    marker=dict(color=color, opacity=0.5, size=5), name="Prediksi",
                ))
                min_val = min(yt_sample.min(), yp_sample.min())
                max_val = max(yt_sample.max(), yp_sample.max())
                fig_ap.add_trace(go.Scatter(
                    x=[min_val, max_val], y=[min_val, max_val], mode="lines",
                    line=dict(color="#EF4444", dash="dash"), name="Ideal (y=x)",
                ))
                fig_ap.update_layout(
                    title=f"Actual vs Predicted — {model_name}",
                    xaxis_title="Harga Aktual (USD)", yaxis_title="Harga Prediksi (USD)",
                    height=380, plot_bgcolor="white", paper_bgcolor="white",
                )
                st.plotly_chart(fig_ap, use_container_width=True)

            with col_r:
                residuals = np.array(y_test) - y_pred
                fig_res = go.Figure()
                fig_res.add_trace(go.Scatter(
                    x=y_pred[idx], y=residuals[idx], mode="markers",
                    marker=dict(color=color, opacity=0.5, size=5), name="Residual",
                ))
                fig_res.add_hline(y=0, line_dash="dash", line_color="#EF4444")
                fig_res.update_layout(
                    title=f"Residual Plot — {model_name}",
                    xaxis_title="Harga Prediksi (USD)", yaxis_title="Residual (Aktual − Prediksi)",
                    height=380, plot_bgcolor="white", paper_bgcolor="white",
                )
                st.plotly_chart(fig_res, use_container_width=True)

            if model_name == "ANN" and "history" in res:
                st.markdown("**📉 Kurva Training ANN**")
                hist = res["history"].history
                epochs_range = list(range(1, len(hist["loss"]) + 1))

                fig_loss = make_subplots(rows=1, cols=2, subplot_titles=["Loss (MSE)", "MAE"])
                fig_loss.add_trace(go.Scatter(x=epochs_range, y=hist["loss"],
                                              name="Train Loss", line=dict(color="#7C3AED")), row=1, col=1)
                if "val_loss" in hist:
                    fig_loss.add_trace(go.Scatter(x=epochs_range, y=hist["val_loss"],
                                                  name="Val Loss", line=dict(color="#F59E0B", dash="dash")), row=1, col=1)
                fig_loss.add_trace(go.Scatter(x=epochs_range, y=hist["mae"],
                                              name="Train MAE", line=dict(color="#7C3AED")), row=1, col=2)
                if "val_mae" in hist:
                    fig_loss.add_trace(go.Scatter(x=epochs_range, y=hist["val_mae"],
                                                  name="Val MAE", line=dict(color="#F59E0B", dash="dash")), row=1, col=2)

                fig_loss.update_layout(height=350, plot_bgcolor="white", paper_bgcolor="white",
                                       legend=dict(orientation="h", yanchor="bottom", y=1.02))
                st.plotly_chart(fig_loss, use_container_width=True)

            with st.expander("⏱️ Detail Waktu Training & Prediksi"):
                st.markdown(f"- **Training Time:** `{metrics.get('Training Time (s)', '—')} s`")
                st.markdown(f"- **Prediction Time:** `{metrics.get('Prediction Time (s)', '—')} s`")

    footer()


# ════════════════════════════════════════════════════════════════
# HALAMAN 4 — FEATURE IMPORTANCE
# ════════════════════════════════════════════════════════════════
def page_feature_importance():
    st.markdown("<h2 style='color:#1A3A5C;'>📌 Feature Importance — Random Forest</h2>", unsafe_allow_html=True)
    st.markdown("Analisis kontribusi setiap fitur terhadap prediksi harga rumah menggunakan Random Forest.")
    st.markdown("---")

    df = load_data()
    X, y, feature_names = preprocess_data(df)

    rf = load_model(RF_PATH)
    if rf is None:
        st.warning(
            "⚠️ Model Random Forest belum dilatih.\n\n"
            "Silakan pergi ke halaman **🤖 Machine Learning** dan klik **Train Model** terlebih dahulu."
        )
        st.stop()

    importances    = rf.feature_importances_
    feature_series = pd.Series(importances, index=feature_names).sort_values(ascending=False)
    top20          = feature_series.head(20).reset_index()
    top20.columns  = ["Feature", "Importance"]
    top20["Rank"]  = range(1, len(top20) + 1)
    top20["Persen (%)"] = (top20["Importance"] * 100).round(3)

    section_header("🏆 Top 20 Feature Importance")

    fig_fi = px.bar(
        top20.sort_values("Importance"), x="Importance", y="Feature", orientation="h",
        title="Top 20 Fitur Paling Berpengaruh (Random Forest)",
        labels={"Importance": "Feature Importance Score", "Feature": "Fitur"},
        color="Importance", color_continuous_scale="Blues", text="Persen (%)",
    )
    fig_fi.update_traces(texttemplate="%{text:.2f}%", textposition="outside")
    fig_fi.update_layout(
        height=600, plot_bgcolor="white", paper_bgcolor="white", coloraxis_showscale=False,
        margin=dict(l=200), yaxis=dict(tickfont=dict(size=12)),
    )
    st.plotly_chart(fig_fi, use_container_width=True)

    col_tbl, col_cum = st.columns([1, 1])

    with col_tbl:
        section_header("📋 Tabel Feature Importance")
        display_df = top20[["Rank", "Feature", "Importance", "Persen (%)"]].copy()
        display_df["Importance"] = display_df["Importance"].round(6)
        st.dataframe(
            display_df.style.background_gradient(subset=["Importance"], cmap="Blues"),
            hide_index=True, use_container_width=True, height=480,
        )

    with col_cum:
        section_header("📈 Cumulative Feature Importance")
        top20_sorted = top20.sort_values("Importance", ascending=False).reset_index(drop=True)
        top20_sorted["Cumulative"] = top20_sorted["Importance"].cumsum() * 100

        fig_cum = go.Figure()
        fig_cum.add_trace(go.Bar(
            x=list(range(1, len(top20_sorted) + 1)), y=top20_sorted["Importance"] * 100,
            name="Importance (%)", marker_color="#93C5FD",
        ))
        fig_cum.add_trace(go.Scatter(
            x=list(range(1, len(top20_sorted) + 1)), y=top20_sorted["Cumulative"],
            name="Cumulative (%)", line=dict(color="#1E5FA0", width=3),
            mode="lines+markers", yaxis="y2",
        ))
        fig_cum.add_hline(y=80, line_dash="dash", line_color="#EF4444",
                          annotation_text="80% threshold", yref="y2")

        fig_cum.update_layout(
            title="Cumulative Importance (Top 20 Fitur)", xaxis_title="Ranking Fitur",
            yaxis_title="Importance (%)",
            yaxis2=dict(title="Cumulative (%)", overlaying="y", side="right", range=[0, 110]),
            height=480, plot_bgcolor="white", paper_bgcolor="white",
            legend=dict(orientation="h", yanchor="bottom", y=1.02),
        )
        st.plotly_chart(fig_cum, use_container_width=True)

    section_header("💡 Penjelasan Fitur Paling Berpengaruh")

    feature_desc = {
        "sqft_living":   ("📐 Luas Bangunan (sqft_living)", "Luas area hunian dalam satuan kaki persegi. Semakin besar rumah, semakin tinggi harga yang ditawarkan. Ini adalah faktor paling dominan dalam menentukan harga rumah."),
        "sqft_above":    ("🏠 Luas Lantai Atas (sqft_above)", "Luas bagian atas (di atas tanah) dari bangunan. Berkorelasi kuat dengan total luas bangunan dan menjadi proxy utama ukuran rumah."),
        "bathrooms":     ("🚿 Jumlah Kamar Mandi (bathrooms)", "Lebih banyak kamar mandi biasanya mengindikasikan rumah yang lebih besar dan lebih mewah, meningkatkan nilai properti secara signifikan."),
        "bedrooms":      ("🛏️ Jumlah Kamar Tidur (bedrooms)", "Jumlah kamar tidur mencerminkan kapasitas hunian. Namun terlalu banyak kamar tidur dalam rumah kecil bisa menurunkan nilai."),
        "sqft_lot":      ("🌳 Luas Tanah (sqft_lot)", "Luas total kavling tanah. Lahan yang luas meningkatkan nilai properti, terutama di area premium."),
        "yr_built":      ("📅 Tahun Dibangun (yr_built)", "Rumah yang lebih baru cenderung memiliki harga lebih tinggi karena kondisi bangunan yang lebih baik dan teknologi konstruksi modern."),
        "waterfront":    ("🌊 Waterfront (waterfront)", "Properti di tepi air (danau/sungai/laut) memiliki nilai premium sangat tinggi karena pemandangan dan gaya hidup yang ditawarkan."),
        "view":          ("🏔️ Kualitas Pemandangan (view)", "Skor pemandangan rumah (0–4). Pemandangan yang indah meningkatkan daya tarik dan nilai jual properti."),
        "condition":     ("🔧 Kondisi Rumah (condition)", "Penilaian kondisi fisik bangunan (1–5). Kondisi yang lebih baik mengurangi biaya renovasi dan meningkatkan harga."),
        "floors":        ("🏢 Jumlah Lantai (floors)", "Rumah bertingkat biasanya memiliki luas yang lebih besar dan nilai arsitektur yang lebih tinggi."),
    }

    top5 = top20_sorted.head(5)
    for _, row in top5.iterrows():
        feat  = row["Feature"]
        score = row["Importance"]
        rank  = int(row["Rank"])

        title, desc = None, None
        for key, (t, d) in feature_desc.items():
            if key in feat:
                title, desc = t, d
                break

        if title is None:
            title = f"📊 {feat}"
            desc  = f"Fitur ini berkontribusi signifikan terhadap prediksi harga dengan skor importance {score:.4f}."

        with st.expander(f"#{rank} — {title} ({score*100:.2f}%)"):
            st.markdown(f"**Penjelasan:** {desc}")
            st.progress(float(score / top20_sorted['Importance'].max()))
            st.markdown(f"**Importance Score:** `{score:.6f}`")

    with st.expander("📋 Lihat Semua Feature Importance"):
        all_fi = feature_series.reset_index()
        all_fi.columns = ["Feature", "Importance"]
        all_fi["Persen (%)"] = (all_fi["Importance"] * 100).round(4)
        all_fi.insert(0, "Rank", range(1, len(all_fi) + 1))
        st.dataframe(all_fi, hide_index=True, use_container_width=True)

    footer()


# ════════════════════════════════════════════════════════════════
# HALAMAN 5 — PERBANDINGAN MODEL
# ════════════════════════════════════════════════════════════════
def page_compare():
    st.markdown("<h2 style='color:#1A3A5C;'>⚖️ Perbandingan Model</h2>", unsafe_allow_html=True)
    st.markdown("Bandingkan performa Linear Regression, Random Forest, dan ANN secara head-to-head.")
    st.markdown("---")

    df = load_data()
    X, y, feature_names = preprocess_data(df)
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    if not models_exist():
        st.warning(
            "⚠️ Belum semua model tersedia.\n\n"
            "Silakan pergi ke halaman **🤖 Machine Learning** dan latih model terlebih dahulu."
        )
        st.stop()

    @st.cache_data(show_spinner="📂 Memuat model...")
    def load_all_predictions():
        lr  = load_model(LR_PATH)
        rf  = load_model(RF_PATH)
        ann = load_ann(ANN_PATH)
        sc  = load_model(SCALER_PATH)

        results = {}

        if lr:
            t = time.time()
            yp = lr.predict(X_test)
            pt = time.time() - t
            m  = compute_metrics(y_test, yp)
            m["Prediction Time (s)"] = round(pt, 6)
            results["Linear Regression"] = {"metrics": m, "y_pred": yp}

        if rf:
            t = time.time()
            yp = rf.predict(X_test)
            pt = time.time() - t
            m  = compute_metrics(y_test, yp)
            m["Prediction Time (s)"] = round(pt, 6)
            results["Random Forest"] = {"metrics": m, "y_pred": yp}

        if ann and sc:
            X_sc = sc.transform(X_test)
            t  = time.time()
            yp = ann.predict(X_sc, verbose=0).flatten()
            pt = time.time() - t
            m  = compute_metrics(y_test, yp)
            m["Prediction Time (s)"] = round(pt, 4)
            results["ANN"] = {"metrics": m, "y_pred": yp}

        return results

    results = load_all_predictions()

    if not results:
        st.error("❌ Tidak dapat memuat model. Pastikan semua model sudah dilatih.")
        st.stop()

    rows = []
    for model_name, res in results.items():
        m = res["metrics"]
        rows.append({
            "Model": model_name, "MAE ($)": round(m["MAE"], 2), "MSE ($²)": round(m["MSE"], 2),
            "RMSE ($)": round(m["RMSE"], 2), "R²": round(m["R²"], 4),
            "Pred Time (s)": m.get("Prediction Time (s)", "—"),
        })

    compare_df = pd.DataFrame(rows)

    best_rmse  = compare_df.loc[compare_df["RMSE ($)"].idxmin(), "Model"]
    best_r2    = compare_df.loc[compare_df["R²"].idxmax(), "Model"]
    best_model = best_rmse

    colors = {"Linear Regression": "#1E5FA0", "Random Forest": "#059669", "ANN": "#7C3AED"}

    section_header("🏆 Ringkasan Metrik Semua Model")

    for model_name, res in results.items():
        m = res["metrics"]
        is_best = model_name == best_model
        badge   = ' <span class="best-badge">🏆 BEST MODEL</span>' if is_best else ""

        st.markdown(
            f"<h4 style='color:{colors.get(model_name,'#1A3A5C')};'>{model_name}{badge}</h4>",
            unsafe_allow_html=True,
        )

        c1, c2, c3, c4 = st.columns(4)
        for col, icon, label, val in [
            (c1, "📉", "MAE",  f"${m['MAE']:,.2f}"),
            (c2, "📉", "MSE",  f"${m['MSE']:,.0f}"),
            (c3, "📉", "RMSE", f"${m['RMSE']:,.2f}"),
            (c4, "📈", "R²",   f"{m['R²']:.4f}"),
        ]:
            with col:
                st.markdown(metric_card_html(icon, label, val), unsafe_allow_html=True)

        st.markdown("<br>", unsafe_allow_html=True)

    st.markdown("---")

    section_header("📋 Tabel Perbandingan Lengkap")

    def highlight_best(df_style):
        styles = []
        for _, row in df_style.iterrows():
            if row["Model"] == best_model:
                styles.append(["background-color: #D1FAE5; font-weight: bold;"] * len(row))
            else:
                styles.append([""] * len(row))
        return pd.DataFrame(styles, index=df_style.index, columns=df_style.columns)

    st.dataframe(
        compare_df.style.apply(highlight_best, axis=None),
        hide_index=True, use_container_width=True,
    )

    st.markdown(
        f"""
        <div style='background:#D1FAE5; border-radius:10px; padding:12px 20px; margin-top:12px;
                    border-left:4px solid #059669;'>
            🏆 <b>Model Terbaik berdasarkan RMSE terkecil:</b>
            <span style='color:#065F46; font-size:18px; font-weight:700;'>{best_model}</span>
            &nbsp;&nbsp;|&nbsp;&nbsp;
            🎯 <b>Model Terbaik berdasarkan R² terbesar:</b>
            <span style='color:#065F46; font-size:18px; font-weight:700;'>{best_r2}</span>
        </div>
        """,
        unsafe_allow_html=True,
    )

    st.markdown("<br>", unsafe_allow_html=True)

    section_header("📊 Visualisasi Perbandingan")

    model_names = compare_df["Model"].tolist()
    bar_colors  = [colors.get(m, "#1E5FA0") for m in model_names]

    col_b1, col_b2, col_b3 = st.columns(3)

    with col_b1:
        fig_mae = go.Figure(go.Bar(
            x=model_names, y=compare_df["MAE ($)"], marker_color=bar_colors,
            text=compare_df["MAE ($)"].apply(lambda v: f"${v:,.0f}"), textposition="auto",
        ))
        fig_mae.update_layout(title="MAE — Semakin Kecil Semakin Baik", yaxis_title="MAE ($)",
                              height=380, plot_bgcolor="white", paper_bgcolor="white", showlegend=False)
        st.plotly_chart(fig_mae, use_container_width=True)

    with col_b2:
        fig_rmse = go.Figure(go.Bar(
            x=model_names, y=compare_df["RMSE ($)"], marker_color=bar_colors,
            text=compare_df["RMSE ($)"].apply(lambda v: f"${v:,.0f}"), textposition="auto",
        ))
        fig_rmse.update_layout(title="RMSE — Semakin Kecil Semakin Baik", yaxis_title="RMSE ($)",
                               height=380, plot_bgcolor="white", paper_bgcolor="white", showlegend=False)
        st.plotly_chart(fig_rmse, use_container_width=True)

    with col_b3:
        fig_r2 = go.Figure(go.Bar(
            x=model_names, y=compare_df["R²"], marker_color=bar_colors,
            text=compare_df["R²"].apply(lambda v: f"{v:.4f}"), textposition="auto",
        ))
        fig_r2.update_layout(title="R² — Semakin Besar Semakin Baik", yaxis_title="R²",
                             yaxis=dict(range=[0, 1]), height=380,
                             plot_bgcolor="white", paper_bgcolor="white", showlegend=False)
        st.plotly_chart(fig_r2, use_container_width=True)

    section_header("🕸️ Radar Chart Perbandingan")

    metrics_for_radar = ["MAE ($)", "RMSE ($)", "R²"]
    radar_df = compare_df[["Model"] + metrics_for_radar].copy()

    for col_r in ["MAE ($)", "RMSE ($)"]:
        max_val = radar_df[col_r].max()
        min_val = radar_df[col_r].min()
        if max_val != min_val:
            radar_df[col_r] = 1 - (radar_df[col_r] - min_val) / (max_val - min_val)
        else:
            radar_df[col_r] = 1.0

    max_r2 = radar_df["R²"].max()
    min_r2 = radar_df["R²"].min()
    if max_r2 != min_r2:
        radar_df["R²"] = (radar_df["R²"] - min_r2) / (max_r2 - min_r2)
    else:
        radar_df["R²"] = 1.0

    categories = ["MAE (↓)", "RMSE (↓)", "R² (↑)"]

    fig_radar = go.Figure()
    for _, row_r in radar_df.iterrows():
        vals = [row_r["MAE ($)"], row_r["RMSE ($)"], row_r["R²"]]
        vals_closed = vals + [vals[0]]
        fig_radar.add_trace(go.Scatterpolar(
            r=vals_closed, theta=categories + [categories[0]], fill="toself",
            name=row_r["Model"], line_color=colors.get(row_r["Model"], "#1E5FA0"), opacity=0.7,
        ))

    fig_radar.update_layout(
        polar=dict(radialaxis=dict(visible=True, range=[0, 1])), height=450,
        title="Radar Chart Perbandingan Model (Dinormalisasi)",
        legend=dict(orientation="h", yanchor="bottom", y=1.08),
    )
    st.plotly_chart(fig_radar, use_container_width=True)

    section_header("📉 Actual vs Predicted — Semua Model")

    fig_avp = make_subplots(rows=1, cols=len(results), subplot_titles=list(results.keys()))
    y_test_arr = np.array(y_test)

    for i, (model_name, res) in enumerate(results.items()):
        y_pred = res["y_pred"]
        sample_idx = np.random.choice(len(y_test_arr), min(300, len(y_test_arr)), replace=False)

        fig_avp.add_trace(
            go.Scatter(
                x=y_test_arr[sample_idx], y=y_pred[sample_idx], mode="markers",
                marker=dict(color=colors.get(model_name, "#1E5FA0"), opacity=0.5, size=5),
                name=model_name, showlegend=(i == 0),
            ),
            row=1, col=i + 1,
        )

        min_v = min(y_test_arr.min(), y_pred.min())
        max_v = max(y_test_arr.max(), y_pred.max())
        fig_avp.add_trace(
            go.Scatter(x=[min_v, max_v], y=[min_v, max_v], mode="lines",
                      line=dict(color="#EF4444", dash="dash"), name="Ideal", showlegend=(i == 0)),
            row=1, col=i + 1,
        )

    fig_avp.update_layout(height=380, plot_bgcolor="white", paper_bgcolor="white",
                          title_text="Actual vs Predicted (Semua Model)")
    st.plotly_chart(fig_avp, use_container_width=True)

    footer()


# ════════════════════════════════════════════════════════════════
# HALAMAN 6 — PREDIKSI
# ════════════════════════════════════════════════════════════════
def page_predict():
    st.markdown("<h2 style='color:#1A3A5C;'>🔮 Prediksi Harga Rumah</h2>", unsafe_allow_html=True)
    st.markdown("Masukkan spesifikasi rumah dan pilih model untuk mendapatkan estimasi harga.")
    st.markdown("---")

    if not models_exist():
        st.warning(
            "⚠️ Model belum tersedia.\n\n"
            "Silakan buka halaman **🤖 Machine Learning** dan latih model terlebih dahulu."
        )
        st.stop()

    df_raw = load_data()

    df_clean = df_raw.copy()
    for c in DROP_COLS:
        if c in df_clean.columns:
            df_clean.drop(columns=[c], inplace=True)
    df_clean.dropna(inplace=True)

    city_list     = sorted(df_clean["city"].unique().tolist())     if "city"     in df_clean.columns else []
    statezip_list = sorted(df_clean["statezip"].unique().tolist()) if "statezip" in df_clean.columns else []
    y_series      = df_clean[TARGET]

    rf_saved = load_model(RF_PATH)
    if rf_saved and hasattr(rf_saved, "feature_names_in_"):
        trained_columns = list(rf_saved.feature_names_in_)
    else:
        _, _, trained_columns = preprocess_data(df_raw)

    section_header("📝 Form Input Spesifikasi Rumah")

    with st.form("prediction_form"):
        col1, col2, col3 = st.columns(3)

        with col1:
            st.markdown("**🛏️ Ruang & Kamar**")
            bedrooms  = st.number_input("Bedrooms (Kamar Tidur)", 0, 20, 3, 1)
            bathrooms = st.number_input("Bathrooms (Kamar Mandi)", 0.0, 15.0, 2.0, 0.25)
            floors    = st.number_input("Floors (Lantai)", 1.0, 5.0, 1.0, 0.5)
            condition = st.slider("Condition (Kondisi 1–5)", 1, 5, 3)
            view      = st.slider("View (Pemandangan 0–4)", 0, 4, 0)

        with col2:
            st.markdown("**📐 Luas Area**")
            sqft_living   = st.number_input("Sqft Living (luas hunian)", 200, 15000, 2000, 50)
            sqft_lot      = st.number_input("Sqft Lot (luas tanah)", 500, 1_000_000, 5000, 100)
            sqft_above    = st.number_input("Sqft Above (luas lantai atas)", 200, 10000, 1500, 50)
            sqft_basement = st.number_input("Sqft Basement (luas basement)", 0, 5000, 0, 50)
            waterfront    = st.selectbox("Waterfront (tepi air)", [0, 1],
                                         format_func=lambda x: "Ya (1)" if x == 1 else "Tidak (0)")

        with col3:
            st.markdown("**📅 Tahun & Lokasi**")
            yr_built     = st.number_input("Year Built (tahun dibangun)", 1900, 2024, 2000, 1)
            yr_renovated = st.number_input("Year Renovated (tahun renovasi, 0=belum)", 0, 2024, 0, 1)

            if city_list:
                city = st.selectbox("City (Kota)", city_list)
            else:
                city = st.text_input("City (Kota)", "Seattle")

            if statezip_list:
                statezip = st.selectbox("Statezip (Kode Pos)", statezip_list)
            else:
                statezip = st.text_input("Statezip (Kode Pos)", "WA 98001")

            model_choice = st.selectbox("🤖 Model yang Digunakan",
                                        ["Random Forest", "Linear Regression", "ANN"])

        st.markdown("<br>", unsafe_allow_html=True)
        col_btn1, col_btn2 = st.columns([2, 1])
        with col_btn1:
            submitted = st.form_submit_button("🔮 Prediksi Harga", use_container_width=True)
        with col_btn2:
            reset = st.form_submit_button("🔄 Reset", use_container_width=True)

    if submitted:
        input_dict = {
            "bedrooms": bedrooms, "bathrooms": bathrooms, "sqft_living": sqft_living,
            "sqft_lot": sqft_lot, "floors": floors, "waterfront": waterfront, "view": view,
            "condition": condition, "sqft_above": sqft_above, "sqft_basement": sqft_basement,
            "yr_built": yr_built, "yr_renovated": yr_renovated, "city": city, "statezip": statezip,
        }

        input_df = pd.DataFrame([input_dict])

        cat_present = [c for c in CAT_COLS if c in input_df.columns]
        input_enc = pd.get_dummies(input_df, columns=cat_present, drop_first=False)

        for col in trained_columns:
            if col not in input_enc.columns:
                input_enc[col] = 0.0

        input_enc = input_enc[trained_columns].astype(float)

        predicted_price = None
        error_msg = None

        try:
            if model_choice == "Linear Regression":
                lr_model = load_model(LR_PATH)
                if lr_model:
                    predicted_price = lr_model.predict(input_enc)[0]
                else:
                    error_msg = "Model Linear Regression tidak ditemukan."

            elif model_choice == "Random Forest":
                rf_model = load_model(RF_PATH)
                if rf_model:
                    predicted_price = rf_model.predict(input_enc)[0]
                else:
                    error_msg = "Model Random Forest tidak ditemukan."

            elif model_choice == "ANN":
                ann_model = load_ann(ANN_PATH)
                scaler = load_model(SCALER_PATH)
                if ann_model and scaler:
                    input_sc = scaler.transform(input_enc)
                    predicted_price = ann_model.predict(input_sc, verbose=0).flatten()[0]
                else:
                    error_msg = "Model ANN atau Scaler tidak ditemukan."

        except Exception as e:
            error_msg = f"Error saat prediksi: {str(e)}"

        st.markdown("---")
        section_header("💰 Hasil Prediksi")

        if error_msg:
            st.error(f"❌ {error_msg}")
        elif predicted_price is not None:
            predicted_price = max(0, float(predicted_price))
            category = price_category(predicted_price, y_series)

            col_res, col_detail = st.columns([1, 1])

            with col_res:
                st.markdown(
                    f"""
                    <div class="prediction-box">
                        <div class="pred-label">Estimasi Harga Rumah</div>
                        <div class="pred-price">{format_currency(predicted_price)}</div>
                        <div style="opacity:0.7; font-size:13px;">menggunakan {model_choice}</div>
                    </div>
                    """,
                    unsafe_allow_html=True,
                )

                st.markdown("<br>", unsafe_allow_html=True)

                if category == "high":
                    badge_html = '<div class="price-high">🔴 HIGH PRICE — Di atas Q66</div>'
                    category_desc = f"Harga ini berada di kuartil atas (> Q66 = {format_currency(y_series.quantile(0.66))})."
                elif category == "medium":
                    badge_html = '<div class="price-medium">🟡 MEDIUM PRICE — Q33 – Q66</div>'
                    category_desc = f"Harga ini berada di rentang menengah ({format_currency(y_series.quantile(0.33))} – {format_currency(y_series.quantile(0.66))})."
                else:
                    badge_html = '<div class="price-low">🟢 LOW PRICE — Di bawah Q33</div>'
                    category_desc = f"Harga ini berada di kuartil bawah (< Q33 = {format_currency(y_series.quantile(0.33))})."

                st.markdown(badge_html, unsafe_allow_html=True)
                st.markdown(f"<br><p style='color:#6B7280;'>{category_desc}</p>", unsafe_allow_html=True)

            with col_detail:
                st.markdown("**📋 Ringkasan Input**")
                summary = {
                    "Spesifikasi": [
                        "Kamar Tidur", "Kamar Mandi", "Lantai", "Kondisi", "Pemandangan",
                        "Waterfront", "Luas Hunian (sqft)", "Luas Tanah (sqft)",
                        "Luas Atas (sqft)", "Luas Basement (sqft)", "Tahun Dibangun",
                        "Tahun Renovasi", "Kota", "Kode Pos",
                    ],
                    "Nilai": [
                        bedrooms, bathrooms, floors, f"{condition}/5", f"{view}/4",
                        "Ya" if waterfront == 1 else "Tidak", f"{sqft_living:,}", f"{sqft_lot:,}",
                        f"{sqft_above:,}", f"{sqft_basement:,}", yr_built,
                        yr_renovated if yr_renovated > 0 else "Belum Pernah", city, statezip,
                    ],
                }
                st.dataframe(pd.DataFrame(summary), hide_index=True, use_container_width=True, height=450)

            st.markdown("<br>", unsafe_allow_html=True)

            fig_ref = go.Figure()
            fig_ref.add_trace(go.Histogram(
                x=y_series, nbinsx=60, marker_color="#93C5FD", opacity=0.7, name="Distribusi Harga",
            ))
            fig_ref.add_vline(
                x=predicted_price, line_dash="solid", line_color="#EF4444", line_width=3,
                annotation_text=f"Prediksi: {format_currency(predicted_price)}",
                annotation_position="top right", annotation_font_color="#EF4444",
            )
            fig_ref.add_vline(x=y_series.mean(), line_dash="dash", line_color="#6B7280",
                              annotation_text="Mean", annotation_position="top left")
            fig_ref.update_layout(
                title="Posisi Harga Prediksi dalam Distribusi Dataset",
                xaxis_title="Harga (USD)", yaxis_title="Frekuensi", height=320,
                plot_bgcolor="white", paper_bgcolor="white", showlegend=False,
            )
            st.plotly_chart(fig_ref, use_container_width=True)

    elif reset:
        st.rerun()

    footer()


# ════════════════════════════════════════════════════════════════
# HALAMAN 7 — KESIMPULAN
# ════════════════════════════════════════════════════════════════
def page_conclusion():
    st.markdown("<h2 style='color:#1A3A5C;'>📝 Kesimpulan & Rekomendasi</h2>", unsafe_allow_html=True)
    st.markdown("Ringkasan hasil penelitian prediksi harga rumah menggunakan tiga algoritma machine learning.")
    st.markdown("---")

    if not models_exist():
        st.warning(
            "⚠️ Model belum tersedia.\n\n"
            "Silakan buka halaman **🤖 Machine Learning** dan latih model terlebih dahulu."
        )
        st.stop()

    df = load_data()
    X, y, feature_names = preprocess_data(df)
    _, X_test, _, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    @st.cache_data(show_spinner="📊 Menghitung metrik akhir...")
    def get_all_metrics():
        results = {}

        lr = load_model(LR_PATH)
        if lr:
            yp = lr.predict(X_test)
            results["Linear Regression"] = compute_metrics(y_test, yp)

        rf = load_model(RF_PATH)
        if rf:
            yp = rf.predict(X_test)
            results["Random Forest"] = compute_metrics(y_test, yp)

        ann = load_ann(ANN_PATH)
        sc  = load_model(SCALER_PATH)
        if ann and sc:
            X_sc = sc.transform(X_test)
            yp = ann.predict(X_sc, verbose=0).flatten()
            results["ANN"] = compute_metrics(y_test, yp)

        return results

    all_metrics = get_all_metrics()

    if not all_metrics:
        st.error("❌ Tidak dapat memuat metrik. Pastikan semua model sudah dilatih.")
        st.stop()

    best_model_name = min(all_metrics, key=lambda m: all_metrics[m]["RMSE"])
    best_metrics    = all_metrics[best_model_name]

    colors = {"Linear Regression": "#1E5FA0", "Random Forest": "#059669", "ANN": "#7C3AED"}

    st.markdown(
        f"""
        <div style='background:linear-gradient(135deg,#1A3A5C,#1E5FA0);
                    border-radius:20px; padding:40px; text-align:center; margin-bottom:32px;'>
            <div style='font-size:48px; margin-bottom:12px;'>🏆</div>
            <div style='color:rgba(255,255,255,0.7); font-size:14px; font-weight:500;
                        text-transform:uppercase; letter-spacing:0.1em; margin-bottom:8px;'>
                Model Terbaik
            </div>
            <div style='color:white; font-size:36px; font-weight:700; margin-bottom:16px;'>
                {best_model_name}
            </div>
            <div style='display:flex; justify-content:center; gap:32px; flex-wrap:wrap;'>
                <div>
                    <div style='color:rgba(255,255,255,0.6); font-size:12px;'>RMSE</div>
                    <div style='color:white; font-size:22px; font-weight:700;'>
                        {format_currency(best_metrics['RMSE'])}
                    </div>
                </div>
                <div>
                    <div style='color:rgba(255,255,255,0.6); font-size:12px;'>MAE</div>
                    <div style='color:white; font-size:22px; font-weight:700;'>
                        {format_currency(best_metrics['MAE'])}
                    </div>
                </div>
                <div>
                    <div style='color:rgba(255,255,255,0.6); font-size:12px;'>R²</div>
                    <div style='color:white; font-size:22px; font-weight:700;'>
                        {best_metrics['R²']:.4f}
                    </div>
                </div>
            </div>
        </div>
        """,
        unsafe_allow_html=True,
    )

    section_header("📊 Ringkasan Metrik Semua Model")

    cols = st.columns(len(all_metrics))
    for col, (model_name, metrics) in zip(cols, all_metrics.items()):
        is_best = model_name == best_model_name
        border  = "4px solid #059669" if is_best else "4px solid #E5E7EB"
        badge   = "🏆 BEST" if is_best else ""

        with col:
            st.markdown(
                f"""
                <div style='background:white; border-radius:16px; padding:20px;
                            box-shadow:0 2px 12px rgba(0,0,0,0.06); border-top:{border};
                            text-align:center;'>
                    <div style='font-size:20px; font-weight:700; color:{colors.get(model_name,"#1A3A5C")};
                                margin-bottom:4px;'>{model_name}</div>
                    <div style='color:#059669; font-weight:600; font-size:12px; margin-bottom:12px;'>{badge}</div>
                    <div style='color:#6B7280; font-size:12px;'>RMSE</div>
                    <div style='font-size:20px; font-weight:700; color:#1A3A5C;'>{format_currency(metrics['RMSE'])}</div>
                    <div style='color:#6B7280; font-size:12px; margin-top:8px;'>MAE</div>
                    <div style='font-size:16px; font-weight:600; color:#374151;'>{format_currency(metrics['MAE'])}</div>
                    <div style='color:#6B7280; font-size:12px; margin-top:8px;'>R²</div>
                    <div style='font-size:16px; font-weight:600; color:#374151;'>{metrics['R²']:.4f}</div>
                </div>
                """,
                unsafe_allow_html=True,
            )

    st.markdown("<br>", unsafe_allow_html=True)

    section_header("💬 Kesimpulan Penelitian")

    best_r2_name  = max(all_metrics, key=lambda m: all_metrics[m]["R²"])
    worst_r2_name = min(all_metrics, key=lambda m: all_metrics[m]["R²"])

    r2_best   = all_metrics[best_r2_name]["R²"]
    r2_worst  = all_metrics[worst_r2_name]["R²"]
    rmse_best = all_metrics[best_model_name]["RMSE"]
    mae_best  = all_metrics[best_model_name]["MAE"]

    if r2_best >= 0.90:
        performa = "sangat baik (R² ≥ 0.90)"
    elif r2_best >= 0.80:
        performa = "baik (R² antara 0.80–0.90)"
    elif r2_best >= 0.70:
        performa = "cukup baik (R² antara 0.70–0.80)"
    else:
        performa = "perlu ditingkatkan (R² < 0.70)"

    auto_conclusion = f"""
Penelitian ini berhasil mengimplementasikan dan membandingkan tiga algoritma machine learning
untuk prediksi harga rumah berdasarkan dataset ~4.600 data properti.

Berdasarkan evaluasi menggunakan metrik MAE, MSE, RMSE, dan R² pada data testing (20%):

**1. Performa Model Terbaik**
Model **{best_model_name}** menunjukkan performa terbaik dengan RMSE sebesar
**{format_currency(rmse_best)}** dan nilai R² sebesar **{best_metrics['R²']:.4f}**,
artinya model mampu menjelaskan **{best_metrics['R²']*100:.1f}%** variabilitas harga rumah.

**2. Perbandingan Antar Model**
- Model dengan R² tertinggi adalah **{best_r2_name}** (R² = {r2_best:.4f})
- Model dengan R² terendah adalah **{worst_r2_name}** (R² = {r2_worst:.4f})
- Selisih performa antar model menunjukkan bahwa kompleksitas model {'berpengaruh signifikan' if (r2_best - r2_worst) > 0.05 else 'tidak terlalu signifikan'} terhadap akurasi prediksi.

**3. Kualitas Prediksi Keseluruhan**
Performa terbaik dicapai dengan hasil yang **{performa}**, yang
{'cukup memadai' if r2_best >= 0.75 else 'masih perlu peningkatan lebih lanjut'}
untuk aplikasi dunia nyata di bidang valuasi properti.

**4. Fitur Paling Berpengaruh**
Berdasarkan analisis Random Forest, fitur dominan adalah **luas bangunan (sqft_living)**
yang memiliki pengaruh terbesar terhadap harga rumah, diikuti oleh lokasi, jumlah kamar mandi,
dan kondisi bangunan.
"""

    st.markdown(auto_conclusion)

    section_header("✅ Rekomendasi")

    rec_tabs = st.tabs(["🏭 Rekomendasi Model", "🔧 Rekomendasi Teknis", "📈 Pengembangan Lebih Lanjut"])

    with rec_tabs[0]:
        st.markdown(
            f"""
            ### 🎯 Model yang Direkomendasikan: **{best_model_name}**

            **Alasan:**
            - Memiliki RMSE terkecil = **{format_currency(rmse_best)}**
            - Nilai R² terbaik = **{best_metrics['R²']:.4f}**
            - Seimbang antara akurasi dan interpretabilitas

            **Kapan menggunakan masing-masing model:**

            | Model | Cocok Digunakan Ketika |
            |-------|----------------------|
            | 📏 Linear Regression | Butuh model sederhana dan cepat, interpretabilitas tinggi |
            | 🌲 Random Forest | Data kompleks dengan banyak fitur non-linear, butuh feature importance |
            | 🧠 ANN | Dataset sangat besar, pola sangat kompleks, optimasi performa maksimal |
            """
        )

    with rec_tabs[1]:
        st.markdown(
            """
            ### 🔧 Rekomendasi Teknis untuk Peningkatan Model

            **Preprocessing:**
            - Coba hapus atau cap outlier ekstrem sebelum training
            - Tambahkan feature engineering (rasio luas/kamar, umur rumah, dll.)
            - Uji label encoding vs target encoding untuk kolom kategorikal

            **Hyperparameter Tuning:**
            - Random Forest: GridSearchCV/RandomizedSearchCV untuk n_estimators, max_depth
            - ANN: Eksperimen dengan learning rate, jumlah neuron, dropout rate
            - Cross-validation K-Fold untuk validasi yang lebih robust

            **Fitur Tambahan:**
            - Koordinat geografis (latitude/longitude) sebagai fitur lokasi
            - Jarak ke pusat kota / fasilitas umum
            - Tingkat kejahatan per area (jika tersedia)
            """
        )

    with rec_tabs[2]:
        st.markdown(
            """
            ### 📈 Arah Pengembangan Lebih Lanjut

            **Model Lanjutan:**
            - Gradient Boosting (XGBoost, LightGBM, CatBoost) — sering lebih unggul dari RF
            - Stacking/Blending ensemble dari ketiga model
            - Bayesian Optimization untuk tuning otomatis

            **Data:**
            - Tambah lebih banyak data historis
            - Integrasi data eksternal (suku bunga KPR, inflasi, populasi)
            - Update berkala dengan data properti terkini

            **Deployment:**
            - Buat REST API menggunakan FastAPI / Flask
            - Dockerize aplikasi untuk deployment cloud (AWS, GCP, Azure)
            - Tambahkan pipeline monitoring untuk drift detection
            - Integrasi dengan sistem MLS / database properti real-time
            """
        )

    section_header("📄 Ringkasan Akhir")

    summary_cols = st.columns(3)
    summary_items = [
        ("📊 Dataset", [
            f"Total data: ~{len(df):,} baris", "Fitur awal: 14 variabel",
            "Target: price (USD)", "Split: 80% train / 20% test",
        ]),
        ("⚙️ Preprocessing", [
            "Hapus: date, street, country", "One-Hot Encoding: city, statezip",
            "StandardScaler untuk ANN", "Hapus baris null",
        ]),
        ("🏆 Hasil", [
            f"Model terbaik: {best_model_name}", f"R²: {best_metrics['R²']:.4f}",
            f"RMSE: {format_currency(rmse_best)}", f"MAE: {format_currency(mae_best)}",
        ]),
    ]

    for col, (title, items) in zip(summary_cols, summary_items):
        with col:
            items_html = "".join(f"<li style='margin-bottom:6px;'>{item}</li>" for item in items)
            st.markdown(
                f"""
                <div style='background:white; border-radius:16px; padding:20px;
                            box-shadow:0 2px 12px rgba(0,0,0,0.06); height:100%;'>
                    <h4 style='color:#1A3A5C; margin-top:0;'>{title}</h4>
                    <ul style='color:#374151; padding-left:20px;'>{items_html}</ul>
                </div>
                """,
                unsafe_allow_html=True,
            )

    footer()


# ════════════════════════════════════════════════════════════════
# NAVIGASI SIDEBAR — MENGGANTIKAN FOLDER pages/
# ════════════════════════════════════════════════════════════════
PAGES = {
    "🏠 Home": page_home,
    "📊 EDA": page_eda,
    "🤖 Machine Learning": page_ml,
    "📌 Feature Importance": page_feature_importance,
    "⚖️ Perbandingan Model": page_compare,
    "🔮 Prediksi": page_predict,
    "📝 Kesimpulan": page_conclusion,
}

with st.sidebar:
    st.markdown(
        "<h2 style='color:white; text-align:center;'>🏠 Navigasi</h2>",
        unsafe_allow_html=True,
    )
    selected_page = st.radio("Pilih Halaman:", list(PAGES.keys()), label_visibility="collapsed")

render_sidebar_info()

# Jalankan halaman yang dipilih
PAGES[selected_page]()